repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        args : 
          - --args=-recursive
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
        files: ^development/.*\.tf$