name: 2. Deploy

on: 
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terrafrom Init
        run: terraform init
        working-directory: ./development

      - run: terraform fmt -recursive -check
        working-directory: ./development

      - run: terraform validate
        working-directory: ./development


      - name: Tarraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./development

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./development/tfplan
    
  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Dowload Plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./development

      - run: terraform init
        working-directory: ./development
        
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./development

  


